4552 Update CVarDumper.php for PHP 8.3 changes to highlight_string
yiisoft/yii pull request #4562
Opened 2024-08-18 15:30 UTC by ThePepster

PHP 8.3.0 The resulting HTML of highlight_string has changed.

`'/&lt;\\?php<br \\/>/'` no longer removes the `"<?php\n"` added when using highlight_string().

2024-08-19 05:49 UTC, Arhell reviewed
@marcovtwout

2024-08-19 08:34 UTC, marcovtwout commented
@ThePepster Can you post a simple test case to reproduce the original issue?

2024-08-19 08:41 UTC, marcovtwout requested changes
Could you also add a CHANGELOG line?

2024-08-19 08:41 UTC, marcovtwout commented on framework/utils/CVarDumper.php
> +			self::$_output=preg_replace('/&lt;\\?php(<br \\/>|'."\n".')/','',$result,1);
You can remove the string concats like this:
```php
self::$_output=preg_replace('/&lt;\\?php(<br \\/>|\\n)/','',$result,1);
```

2024-09-18 08:25 UTC, marcovtwout commented
I'll merge this into https://github.com/yiisoft/yii/pull/4553

2024-09-18 08:29 UTC, closed without merging