BBQ JS fix prototype pollution
yiisoft/yii pull request #4571
Opened 2024-11-11 12:10 UTC by kevin-foster-uk

This PR reverts the previous fix for BBQ JS prototype pollution (https://github.com/yiisoft/yii/issues/4570) with a new fix based on the upstream master branch (https://github.com/cowboy/jquery-bbq). This fix addresses only this one issue with a backward compatible fix (return value is always an object).

You will notice that there are bunch of URLs changed from https and http and IE support has been re-added. This brings it back in line with the current state of the upstream master.

A PR has been created on the upstream master to apply the same fix: https://github.com/cowboy/jquery-bbq/pull/65

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

2024-11-11 14:15 UTC, marcovtwout commented
I will await https://github.com/cowboy/jquery-bbq/pull/65 before reviewing this.

2024-11-11 14:33 UTC, kevin-foster-uk commented
> I will await [cowboy/jquery-bbq#65](https://github.com/cowboy/jquery-bbq/pull/65) before reviewing this.

You will probably be waiting forever which is why we bypassed them in the first place.

2024-11-11 15:16 UTC, marcovtwout commented
Perhaps, but even without merge at least there might be reviewers or commenters. I don't want to release too soon since this fix does not seem highly critical. I'll set a reminder to revisit this PR in case it takes too long.

2024-12-09 09:28 UTC, marcovtwout requested changes
@kevin-foster-uk No activity upstream yet, so I reviewed the PR.

This PR currently reverts too much behavior, for example jQuery 1.9+ compatibility. See notes in https://github.com/yiisoft/yii/pull/4563#issuecomment-2357930701

I propose a new PR that bases on yii's current master and only fixes the issue at hand with the two object creation calls.

2024-12-31 14:35 UTC, kevin-foster-uk commented
@marcovtwout I have created a new PR with minimal changes based on the current Yii master code:
https://github.com/yiisoft/yii/pull/4575

2025-02-03 09:09 UTC, marcovtwout commented
Fixed by https://github.com/yiisoft/yii/pull/4575

2025-02-03 09:09 UTC, closed without merging