BBBQ JS - dparam should always return an object
yiisoft/yii pull request #4575
Opened 2024-12-31 14:23 UTC by kevin-foster-uk

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | https://github.com/yiisoft/yii/issues/4570

2025-01-06 14:19 UTC, marcovtwout requested changes

2025-01-06 14:19 UTC, marcovtwout commented on framework/web/js/source/jquery.ba-bbq.min.js
> +($=>{var jq_param_sorted,jq_param_fragment,jq_deparam,jq_deparam_fragment,jq_bbq_pushState,jq_bbq_getState,jq_elemUrlAttr,re_params_fragment,re_fragment,re_no_escape,ajax_crawlable,fragment_prefix,ap
The comment block from previous version is missing.

2025-01-07 09:14 UTC, kevin-foster-uk commented on framework/web/js/source/jquery.ba-bbq.min.js
> +($=>{var jq_param_sorted,jq_param_fragment,jq_deparam,jq_deparam_fragment,jq_bbq_pushState,jq_bbq_getState,jq_elemUrlAttr,re_params_fragment,re_fragment,re_no_escape,ajax_crawlable,fragment_prefix,ap
The build comment removes the doc block. I added it back in manually.

2025-01-07 12:48 UTC, marcovtwout approved these changes

2025-01-07 12:49 UTC, merged

2025-01-07 12:51 UTC, marcovtwout commented
Thanks!